[package]
name = "poise"
version = "0.1.0"
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.9"
once_cell = "1.7.2"
parking_lot = "0.11"
serde_json = "1"
chrono = "0.4.19"
poise_macros = { path = "macros" }