[package]
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"
name = "poise"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
once_cell = "1.7.2"
parking_lot = "0.11"
serde_json = "1"
serenity = { version = "0.10.4", default-features = false, features = ["builder", "cache", "client", "gateway", "model", "utils", "rustls_backend"] }
tokio = "1.4.0"
poise_macros = { path = "macros" }
