on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - MSRV
          - stable
          - beta
          - nightly
          - macOS
          - Windows
          - no features

        include:
          - name: MSRV
            toolchain: 1.51.0
            # don't do doctests because they rely on new features for brevity
            command: cargo test --features collector --lib --tests
          - name: beta
            toolchain: beta
          - name: nightly
            toolchain: nightly
          - name: macOS
            os: macOS-latest
            # don't test simd-json feature because GHA macOS runners break trying to compile
            # simd_json for a recent CPU
            rustflags: " " # non-empty string as to not override it later
            command: cargo test --features collector
          - name: Windows
            os: windows-latest
          - name: no features
            # don't examples because they need collector feature
            command: cargo test --no-default-features --features serenity_rustls --lib --tests
          - name: all features
            command: cargo test --features collector,__internal_simdjson --lib --tests --examples
          - name: native TLS
            command: cargo test --no-default-features --features collector,serenity_native_tls --lib --tests --examples

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain || 'stable' }}
          override: true
      - run: ${{ matrix.command || 'cargo test --features collector' }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags || '-C target-cpu=haswell' }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - run: RUSTFLAGS="-C target-cpu=haswell" cargo clippy --all-features -- -D warnings
